spring.application.name=Tech_Insight_Dashboard
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.redis.autoconfigure.RedisVectorStoreAutoConfiguration

#Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


#Spring Security JWT secret key
security.jwt.secret=${JWT_SECRET:${SecurityKey}}


#Adzuna API credentials
adzuna.app-id=${ADZUNA_APP_ID}
adzuna.app-key=${ADZUNA_APP_KEY}
