spring.application.name=Tech_Insight_Dashboard
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.redis.autoconfigure.RedisVectorStoreAutoConfiguration



JWT_SECRET=${"SecurityKey"}


adzuna.app-id=${ADZUNA_APP_ID}
adzuna.app-key=${ADZUNA_APP_KEY}
